version: 1

update_configs:
  - package_manager: "javascript"
    directory: "./"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "@ui5/fs"
      - match:
          dependency_name: "@ui5/logger"
